### ISSUE TITLE
Cesium terrain tile service has changed

### ISSUE THREAD

**Issue by bertt** [aiunderstand/QuantizedMeshTiles-UnityViewer#1]
The url http://assets.agi.com/stk-terrain/v1/tilesets/world/tiles/{z}/{x}/{y}.terrain is now deprecated :-(, its changed to https://assets.cesium.com/1/{z}{x}/{y}.terrain?v=1.1.0 with a token in the header. 

Sample code: https://github.com/bertt/quantized-mesh-tile-cs/blob/master/samples/console/Program.cs

**Comment by bertt** [comment]
see https://github.com/aiunderstand/QuantizedMeshTiles-UnityViewer/pull/2

**Comment by bertt** [comment]
it seems they do *something*  with the token so it's only temporary valid (like 15 minutes) :-(

**Comment by aiunderstand** [comment]
fixed in latest pr
